apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: backend
  name: backend
spec:
  containers:
  - image: nginx:latest
    name: backend
    envFrom:
      - configMapRef:
          name: db
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
